-- main pipeline script
-- moves data from source through staging to data mart


-- run initialization
-- inserts a new run record into dwh.etl_runs and captures ID in a temp table named current_run (session scoped, meaning current run)
-- INSERT ... RETURNING captures the exact run_id generated by this session atomically - no race condition risk
-- DROP + CREATE - so the temp table is always rebuilt fresh even if the pipeline is re-executed within same session
DROP TABLE IF EXISTS current_run;
CREATE TEMP TABLE current_run (run_id BIGINT);

BEGIN;
WITH new_run AS (
    INSERT INTO dwh.etl_runs (started_at)
    VALUES (CURRENT_TIMESTAMP)
    RETURNING run_id)
INSERT INTO current_run (run_id)
SELECT run_id FROM new_run
;
COMMIT;


-- DQ LOGGING - source.raw_candidates
-- catches records with missing full_name, source, or profile_created_date
BEGIN;
INSERT INTO dwh.dq_log (run_id, table_name, record_id, issue_type)
SELECT (SELECT run_id 
        FROM current_run),
        'source.raw_candidates',
        candidate_id,
        'NULL_VALUE'
FROM source.raw_candidates
WHERE (full_name IS NULL 
       OR source IS NULL 
       OR profile_created_date IS NULL)
ON CONFLICT (table_name, record_id, issue_type) DO NOTHING
;


-- catches records where profile_created_date falls outside the expected range/year window (2020–2030)
INSERT INTO dwh.dq_log (run_id, table_name, record_id, issue_type)
SELECT (SELECT run_id 
        FROM current_run),
        'source.raw_candidates',
        candidate_id,
        'DATE_OUT_OF_RANGE'
FROM source.raw_candidates
WHERE profile_created_date IS NOT NULL
AND (profile_created_date < '2020-01-01' OR profile_created_date > '2030-12-31')
ON CONFLICT (table_name, record_id, issue_type) DO NOTHING
;


-- catches duplicated records
-- composite/natural key: full_name + source + profile_created_date
WITH duplicated AS (SELECT UPPER(full_name) AS full_name, 
                           UPPER(source) AS source, 
                           profile_created_date,
                           MIN(candidate_id) AS min_id
                    FROM source.raw_candidates
                    WHERE full_name IS NOT NULL
                    AND source IS NOT NULL
                    AND profile_created_date IS NOT NULL
                    GROUP BY UPPER(full_name), 
                             UPPER(source), 
                             profile_created_date
                    HAVING COUNT(*) > 1)
INSERT INTO dwh.dq_log (run_id, table_name, record_id, issue_type)
SELECT (SELECT run_id 
        FROM current_run),
        'source.raw_candidates',
       c.candidate_id,
       'DUPLICATE'
FROM source.raw_candidates AS c
INNER JOIN duplicated AS d
ON d.full_name = UPPER(c.full_name)
AND d.source = UPPER(c.source)
AND d.profile_created_date = c.profile_created_date
WHERE c.candidate_id > d.min_id
ON CONFLICT (table_name, record_id, issue_type) DO NOTHING
;
COMMIT;


-- DQ LOGGING - source.raw_applications
-- catches records with missing candidate_id, role_level, or applied_date
BEGIN;
INSERT INTO dwh.dq_log (run_id, table_name, record_id, issue_type)
SELECT (SELECT run_id 
        FROM current_run),
        'source.raw_applications',
        app_id,
        'NULL_VALUE'
FROM source.raw_applications
WHERE (candidate_id IS NULL 
       OR role_level IS NULL 
       OR applied_date IS NULL)
ON CONFLICT (table_name, record_id, issue_type) DO NOTHING
;


-- catches records where role_level is not NULL but does not match the list of allowed ones
INSERT INTO dwh.dq_log (run_id, table_name, record_id, issue_type)
SELECT (SELECT run_id 
        FROM current_run),
        'source.raw_applications',
        app_id,
       'INVALID_CATEGORY'
FROM source.raw_applications
WHERE role_level IS NOT NULL
AND role_level NOT IN ('Junior', 'Senior', 'Executive')
ON CONFLICT (table_name, record_id, issue_type) DO NOTHING
;


-- catches records where decision_date comes before applied_date
INSERT INTO dwh.dq_log (run_id, table_name, record_id, issue_type)
SELECT (SELECT run_id 
        FROM current_run),
        'source.raw_applications',
       app_id,
       'DATE_LOGIC_ERROR'
FROM source.raw_applications
WHERE decision_date IS NOT NULL
AND applied_date IS NOT NULL
AND decision_date < applied_date
ON CONFLICT (table_name, record_id, issue_type) DO NOTHING
;


-- catches records where the linked candidate's profile_created_date appears after the applied_date
INSERT INTO dwh.dq_log (run_id, table_name, record_id, issue_type)
SELECT (SELECT run_id 
        FROM current_run),
        'source.raw_applications',
       a.app_id,
       'DATE_LOGIC_ERROR'
FROM source.raw_applications AS a
INNER JOIN source.raw_candidates AS c ON c.candidate_id = a.candidate_id
WHERE c.profile_created_date IS NOT NULL
AND a.applied_date IS NOT NULL
AND c.profile_created_date > a.applied_date
ON CONFLICT (table_name, record_id, issue_type) DO NOTHING
;


-- catches records where applied_date or decision_date falls outside the expected range (2020–2030)
INSERT INTO dwh.dq_log (run_id, table_name, record_id, issue_type)
SELECT (SELECT run_id 
        FROM current_run),
        'source.raw_applications',
        app_id,
        'DATE_OUT_OF_RANGE'
FROM source.raw_applications
WHERE ((applied_date IS NOT NULL AND (applied_date < '2020-01-01' OR applied_date > '2030-12-31'))
    OR (decision_date IS NOT NULL AND (decision_date < '2020-01-01' OR decision_date > '2030-12-31')))
ON CONFLICT (table_name, record_id, issue_type) DO NOTHING
;


-- catches records where expected_salary is a negative number
INSERT INTO dwh.dq_log (run_id, table_name, record_id, issue_type)
SELECT (SELECT run_id 
        FROM current_run),
        'source.raw_applications',
        app_id,
        'NEGATIVE_NUMBER'
FROM source.raw_applications
WHERE expected_salary IS NOT NULL
AND expected_salary < 0
ON CONFLICT (table_name, record_id, issue_type) DO NOTHING
;


-- catches duplicated records
-- composite/natural key: candidate_id + role_level + applied_date
WITH duplicated AS (SELECT candidate_id, 
                           UPPER(role_level) AS role_level, 
                           applied_date,
                           MIN(app_id) AS min_id
                    FROM source.raw_applications
                    WHERE candidate_id IS NOT NULL
                    AND role_level IS NOT NULL
                    AND applied_date IS NOT NULL
                    GROUP BY candidate_id, 
                             UPPER(role_level), 
                             applied_date
                    HAVING COUNT(*) > 1)
INSERT INTO dwh.dq_log (run_id, table_name, record_id, issue_type)
SELECT (SELECT run_id 
        FROM current_run),
        'source.raw_applications',
       a.app_id,
       'DUPLICATE'
FROM source.raw_applications AS a
INNER JOIN duplicated AS d
ON d.candidate_id = a.candidate_id
AND d.role_level = UPPER(a.role_level)
AND d.applied_date = a.applied_date
WHERE a.app_id > d.min_id
ON CONFLICT (table_name, record_id, issue_type) DO NOTHING
;


-- catches applications where candidate_id has no matching record in source.raw_candidates
INSERT INTO dwh.dq_log (run_id, table_name, record_id, issue_type)
SELECT (SELECT run_id 
        FROM current_run),
        'source.raw_applications',
       a.app_id,
       'MISSING_FK'
FROM source.raw_applications AS a
WHERE a.candidate_id IS NOT NULL
AND NOT EXISTS (SELECT 1 
                FROM source.raw_candidates AS c
                WHERE c.candidate_id = a.candidate_id)
ON CONFLICT (table_name, record_id, issue_type) DO NOTHING
;
COMMIT;


-- DQ LOGGING - source.raw_interviews
-- catches records with missing app_id, interview_date, or outcome
BEGIN;
INSERT INTO dwh.dq_log (run_id, table_name, record_id, issue_type)
SELECT (SELECT run_id 
        FROM current_run),
        'source.raw_interviews',
        interview_id,
        'NULL_VALUE'
FROM source.raw_interviews
WHERE (app_id IS NULL 
      OR interview_date IS NULL 
      OR outcome IS NULL)
ON CONFLICT (table_name, record_id, issue_type) DO NOTHING
;


-- catches records where outcome is not NULL but does not match the allowed ones
INSERT INTO dwh.dq_log (run_id, table_name, record_id, issue_type)
SELECT (SELECT run_id 
        FROM current_run),
        'source.raw_interviews',
       interview_id,
       'INVALID_CATEGORY'
FROM source.raw_interviews
WHERE outcome IS NOT NULL
AND outcome NOT IN ('Passed', 'Rejected', 'No Show')
ON CONFLICT (table_name, record_id, issue_type) DO NOTHING
;


-- catches records where interview_date appears before the linked application/applied_date
INSERT INTO dwh.dq_log (run_id, table_name, record_id, issue_type)
SELECT (SELECT run_id 
        FROM current_run),
        'source.raw_interviews',
       i.interview_id,
       'DATE_LOGIC_ERROR'
FROM source.raw_interviews AS i
INNER JOIN source.raw_applications AS a ON a.app_id = i.app_id
WHERE i.interview_date IS NOT NULL
AND a.applied_date IS NOT NULL
AND i.interview_date < a.applied_date
ON CONFLICT (table_name, record_id, issue_type) DO NOTHING
;


-- catches records where interview_date falls outside the expected range (2020–2030)
INSERT INTO dwh.dq_log (run_id, table_name, record_id, issue_type)
SELECT (SELECT run_id 
        FROM current_run),
        'source.raw_interviews',
        interview_id,
        'DATE_OUT_OF_RANGE'
FROM source.raw_interviews
WHERE interview_date IS NOT NULL
AND (interview_date < '2020-01-01' OR interview_date > '2030-12-31')
ON CONFLICT (table_name, record_id, issue_type) DO NOTHING
;


-- catches duplicated records
-- composite/natural key: app_id + interview_date + outcome
WITH duplicated AS (SELECT app_id, 
                           interview_date, 
                           UPPER(outcome) AS outcome,
                           MIN(interview_id) AS min_id
                    FROM source.raw_interviews
                    WHERE app_id IS NOT NULL
                    AND interview_date IS NOT NULL
                    AND outcome IS NOT NULL
                    GROUP BY app_id, 
                             interview_date, 
                             UPPER(outcome)
                    HAVING COUNT(*) > 1)
INSERT INTO dwh.dq_log (run_id, table_name, record_id, issue_type)
SELECT (SELECT run_id 
        FROM current_run),
        'source.raw_interviews',
       i.interview_id,
       'DUPLICATE'
FROM source.raw_interviews AS i
INNER JOIN duplicated AS d
ON d.app_id = i.app_id
AND d.interview_date = i.interview_date
AND d.outcome = UPPER(i.outcome)
WHERE i.interview_id > d.min_id
ON CONFLICT (table_name, record_id, issue_type) DO NOTHING
;


-- catches interviews where app_id has no matching record in source.raw_applications
INSERT INTO dwh.dq_log (run_id, table_name, record_id, issue_type)
SELECT (SELECT run_id 
        FROM current_run),
        'source.raw_interviews',
       i.interview_id,
       'MISSING_FK'
FROM source.raw_interviews AS i
WHERE i.app_id IS NOT NULL
AND NOT EXISTS (SELECT 1 
                FROM source.raw_applications AS a
                WHERE a.app_id = i.app_id)
ON CONFLICT (table_name, record_id, issue_type) DO NOTHING
;
COMMIT;


-- upsert into dwh.stg_candidates
BEGIN;
INSERT INTO dwh.stg_candidates (candidate_id,
                                full_name,
                                source,
                                profile_created_date,
                                created_at,
                                updated_at)
SELECT candidate_id,
       full_name,
       source,
       profile_created_date,
       CURRENT_TIMESTAMP,
       CURRENT_TIMESTAMP
FROM (SELECT candidate_id,
             full_name,
             source,
             profile_created_date,
             ROW_NUMBER() OVER (PARTITION BY UPPER(full_name), 
                                             UPPER(source), 
                                             profile_created_date
                                ORDER BY candidate_id ASC) AS rn
FROM source.raw_candidates
WHERE full_name IS NOT NULL
AND source IS NOT NULL
AND profile_created_date IS NOT NULL
AND profile_created_date BETWEEN '2020-01-01' AND '2030-12-31') AS deduped
WHERE rn = 1
ON CONFLICT (candidate_id) DO UPDATE
    SET full_name = EXCLUDED.full_name,
        source = EXCLUDED.source,
        profile_created_date = EXCLUDED.profile_created_date,
        updated_at = CURRENT_TIMESTAMP
;
COMMIT;

-- upsert into dwh.stg_applications
BEGIN;
INSERT INTO dwh.stg_applications (app_id,
                                  candidate_id,
                                  role_level,
                                  applied_date,
                                  decision_date,
                                  expected_salary,
                                  created_at,
                                  updated_at)
SELECT app_id,
       candidate_id,
       role_level,
       applied_date,
       decision_date,
       expected_salary,
       CURRENT_TIMESTAMP,
       CURRENT_TIMESTAMP
FROM (SELECT a.app_id,
             a.candidate_id,
             a.role_level,
             a.applied_date,
             a.decision_date,
             a.expected_salary,
             ROW_NUMBER() OVER (PARTITION BY a.candidate_id, 
                                             UPPER(a.role_level), 
                                             a.applied_date
                                ORDER BY a.app_id ASC) AS rn
FROM source.raw_applications AS a
INNER JOIN dwh.stg_candidates AS sc 
ON sc.candidate_id = a.candidate_id
WHERE a.candidate_id IS NOT NULL
AND a.role_level IS NOT NULL
AND a.applied_date IS NOT NULL
AND a.role_level IN ('Junior', 
                     'Senior', 
                     'Executive')
AND (a.decision_date IS NULL OR a.decision_date >= a.applied_date)
AND a.applied_date BETWEEN '2020-01-01' AND '2030-12-31'
AND (a.decision_date IS NULL OR a.decision_date BETWEEN '2020-01-01' AND '2030-12-31')
AND (a.expected_salary IS NULL OR a.expected_salary >= 0)
AND sc.profile_created_date <= a.applied_date) AS deduped
WHERE rn = 1
ON CONFLICT (app_id) DO UPDATE
    SET candidate_id = EXCLUDED.candidate_id,
        role_level = EXCLUDED.role_level,
        applied_date = EXCLUDED.applied_date,
        decision_date = EXCLUDED.decision_date,
        expected_salary = EXCLUDED.expected_salary,
        updated_at = CURRENT_TIMESTAMP
;
COMMIT;


-- upsert into dwh.stg_interviews
BEGIN;
INSERT INTO dwh.stg_interviews (interview_id,
                                app_id,
                                interview_date,
                                outcome,
                                created_at,
                                updated_at)
SELECT interview_id,
       app_id,
       interview_date,
       outcome,
       CURRENT_TIMESTAMP,
       CURRENT_TIMESTAMP
FROM (SELECT i.interview_id,
             i.app_id,
             i.interview_date,
             i.outcome,
             ROW_NUMBER() OVER (PARTITION BY i.app_id, 
                                             i.interview_date, 
                                             UPPER(i.outcome)
                                ORDER BY i.interview_id ASC) AS rn
FROM source.raw_interviews AS i
INNER JOIN dwh.stg_applications AS a 
ON a.app_id = i.app_id
WHERE i.app_id IS NOT NULL
AND i.interview_date IS NOT NULL
AND i.outcome IS NOT NULL
AND i.outcome IN ('Passed', 
                  'Rejected', 
                  'No Show')
AND i.interview_date >= a.applied_date
AND i.interview_date BETWEEN '2020-01-01' AND '2030-12-31') AS deduped
WHERE rn = 1
ON CONFLICT (interview_id) DO UPDATE
    SET app_id = EXCLUDED.app_id,
        interview_date = EXCLUDED.interview_date,
        outcome = EXCLUDED.outcome,
        updated_at = CURRENT_TIMESTAMP
;
COMMIT;

-- upsert into dwh.dm_hiring_process
-- one row equals one application
-- no business logic applied that is not already enforced upstream
-- time_to_decision = decision_date - applied_date (in days); NULL when decision_date IS NULL (meaning application is still active)
-- total_passed_interviews = count of interviews marked as PASSED for this application; 0 when no interviews exist
-- all metrics are being recalculated and overwritten on every run - data mart always reflects current state
-- therefore, this handles active applications receiving a decision_date and interviews being added to existing applications 
BEGIN;
INSERT INTO dwh.dm_hiring_process (app_id,
                                   candidate_name,
                                   candidate_source,
                                   time_to_decision,
                                   total_passed_interviews,
                                   updated_at)
SELECT a.app_id,
       c.full_name AS candidate_name,
       c.source AS candidate_source,
       (a.decision_date - a.applied_date) AS time_to_decision,
       COUNT(i.interview_id) FILTER(WHERE i.outcome = 'Passed') AS total_passed_interviews,
       CURRENT_TIMESTAMP AS updated_at
FROM dwh.stg_applications AS a
INNER JOIN dwh.stg_candidates AS c 
ON c.candidate_id = a.candidate_id
LEFT JOIN dwh.stg_interviews AS i 
ON i.app_id = a.app_id
GROUP BY a.app_id,
         c.full_name,
         c.source,
         a.decision_date,
         a.applied_date
ON CONFLICT (app_id) DO UPDATE
    SET candidate_name = EXCLUDED.candidate_name,
        candidate_source = EXCLUDED.candidate_source,
        time_to_decision = EXCLUDED.time_to_decision,
        total_passed_interviews = EXCLUDED.total_passed_interviews,
        updated_at = CURRENT_TIMESTAMP
;
COMMIT;


/*

-- ad-hoc summary report across all pipeline layers/stages
-- uncomment and run after all the code above to check the summary along with DQ issues found during pipeline run
SELECT (SELECT run_id 
        FROM current_run) AS run_id,
       (SELECT started_at 
        FROM dwh.etl_runs
        WHERE  run_id = (SELECT run_id 
                         FROM current_run)) AS run_started_at,
       (SELECT COUNT(*) 
        FROM source.raw_candidates) AS source_candidates,
       (SELECT COUNT(*) 
        FROM dwh.stg_candidates) AS staging_candidates,
       (SELECT COUNT(*) 
        FROM source.raw_applications) AS source_applications,
       (SELECT COUNT(*) 
        FROM dwh.stg_applications) AS staging_applications,
       (SELECT COUNT(*) 
        FROM source.raw_interviews) AS source_interviews,
       (SELECT COUNT(*) 
        FROM dwh.stg_interviews) AS staging_interviews,
       (SELECT COUNT(*) 
        FROM dwh.dm_hiring_process) AS datamart_records,
       (SELECT COUNT(*) 
        FROM dwh.dq_log
        WHERE  run_id = (SELECT run_id 
                         FROM current_run)) AS dq_issues_new_this_run,
       (SELECT COUNT(*) 
        FROM dwh.dq_log) AS dq_issues_all_time
;

-- DQ issues new this run, by table and type
SELECT table_name,
       issue_type,
       COUNT(*) AS issue_count
FROM dwh.dq_log
WHERE run_id = (SELECT run_id 
                FROM current_run)
GROUP BY table_name, 
         issue_type
ORDER BY table_name, 
         issue_type
;

*/
